- name: Download zsh installer
  get_url: url=https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh dest=/tmp/zsh-installer.sh mode=u+rwx

- name: Execute the zsh-installer.sh
  shell: /tmp/zsh-installer.sh
  args:
      creates: "~/.oh-my-zsh"

- name: Remove the zsh-installer.sh
  file: path=/tmp/zsh-installer.sh state=absent

- copy:
    src: starship.toml
    dest: "~/.config/starship.toml"

- lineinfile:
    path: "~/.zshrc"
    line: 'eval "$(starship init zsh)"'

- copy:
    src: iterm2.json
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/iterm2.json"

- lineinfile:
      path: "~/.zshrc"
      line: alias ls="lsd"

- lineinfile:
    path: "~/.zshrc"
    line: alias g="git"

- community.general.git_config:
    scope: global
    name: user.name
    value: "Vincent Debergue"

- community.general.git_config:
    scope: global
    name: user.email
    value: "{{ email }}"

- community.general.git_config:
    scope: global
    name: alias.co
    value: "checkout"

- community.general.git_config:
    scope: global
    name: alias.ci
    value: "commit"

- community.general.git_config:
    scope: global
    name: alias.s
    value: "status -s"

- blockinfile:
    path: "~/.gitconfig"
    marker: "# MANAGED BY ANSIBLE git delta"
    block: |
      [pager]
        diff = delta
        log = delta
        reflog = delta
        show = delta

      [interactive]
        diffFilter = delta --color-only --features=interactive

      [delta]
        syntax-theme = "Solarized (dark)"
        line-numbers = true
